apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.mysql.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.service.mysql.appSelector }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.mysql.port }}
      targetPort: {{ .Values.service.mysql.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.monica.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.service.monica.appSelector }}
  ports:
    - name: mysql
      protocol: TCP
      port: {{ .Values.service.monica.port }}
      targetPort: {{ .Values.service.monica.targetPort }}
