name: Build/Publish docker image

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: "Publish to k8s"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sed -i -e "s#__PASSWORD__#${{ secrets.MYSQL_PASSWORD }}#g" values.yaml
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint --strict

  deploy:
    name: "Publish to k8s"
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v1
      - name: update password in manifest.yml
        run: sed -i -e "s#__PASSWORD__#${{ secrets.MYSQL_PASSWORD }}#g" values.yaml
      - name: install helm chart
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade monica . --install --namespace=monica --atomic --wait
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}
